using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace PdfiumViewer
{
    internal static partial class NativeMethods
    {
        #region FPDFBitmap
        [DllImport("pdfium.dll")]
        public static extern IntPtr FPDFBitmap_GetBuffer(IntPtr bitmapHandle);

        [DllImport("pdfium.dll")]
        public static extern IntPtr FPDFBitmap_Destroy(IntPtr bitmapHandle);

        [DllImport("pdfium.dll")]
        public static extern int FPDFBitmap_GetWidth(IntPtr bitmapHandle);

        [DllImport("pdfium.dll")]
        public static extern int FPDFBitmap_GetHeight(IntPtr bitmapHandle);

        [DllImport("pdfium.dll")]
        public static extern int FPDFBitmap_GetStride(IntPtr bitmapHandle);

        [DllImport("pdfium.dll")]
        public static extern void FPDF_RenderPageBitmap(IntPtr bitmapHandle, IntPtr page, int start_x, int start_y, int size_x, int size_y, int rotate, FPDF flags);

        [DllImport("pdfium.dll")]
        public static extern IntPtr FPDFBitmap_Create(int width, int height, int alpha);

        [DllImport("pdfium.dll")]
        public static extern void FPDFBitmap_FillRect(IntPtr bitmapHandle, int left, int top, int width, int height, int red, int green, int blue, int alpha);
        #endregion

        #region FPDFText Methods
        /// <summary>
        /// Get number of characters in a page
        /// </summary>
        /// <param name="page">Handle to a text page information structure. Returned by FPDFText_LoadPage function.</param>
        /// <returns>Number of characters in the page. Return -1 for error. Generated characters, like additional space characters, new line characters, are also counted.</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFText_CountChars(IntPtr page);

        /// <summary>
        /// Get Unicode of a character in a page
        /// </summary>
        /// <param name="page">Handle to a text page information structure. Returned by FPDFText_LoadPage function.</param>
        /// <param name="index">Zero-based index of the character</param>
        /// <returns>The Unicode of the particular character. If a character is not encoded in Unicode and Foxit engine can't convert to Unicode, the return value will be zero.</returns>
        [DllImport("pdfium.dll")]
        public static extern uint FPDFText_GetUnicode(IntPtr page, int index);

        /// <summary>
        /// Indicates whether a character is a generated character
        /// "Generated character" is character not actually encoded in the PDF page, but generated by FPDFTEXT engine to keep formatting information. 
        /// This happens in two cases: 
        /// 1) an extra space character will be generated if two characters in the same line appears to be apart quite some space
        /// 2) a new line character will be generated if two consecutive characters appears to be on different line.This characters are useful when doing the search.
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="index">Zero-based index of the character</param>
        /// <returns>TRUE indicates a generated character and FALSE indicates an actual character in the PDF page.</returns>
        [DllImport("pdfium.dll")]
        public static extern bool FPDFText_IsGenerated(IntPtr page, int index);

        /// <summary>
        /// Get the font size of a particular character
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="index">Zero-based index of the character.</param>
        /// <returns>The font size of the particular character, measured in points (about 1/72 inch). This is the typographic size of the font (so called "em size").</returns>
        [DllImport("pdfium.dll")]
        public static extern double FPDFText_GetFontSize(IntPtr page, int index);

        /// <summary>
        /// Get origin position of a particular character
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="index">Zero-based index of the character.</param>
        /// <param name="x">Pointer to a double number receiving X position of the character origin.</param>
        /// <param name="y">Pointer to a double number receiving Y position of the character origin.</param>
        [DllImport("pdfium.dll")]
        public static extern void FPDFText_GetOrigin(IntPtr page, int index, ref double x, ref double y);

        /// <summary>
        /// Get bounding box of a particular character
        /// 
        /// Comment: All positions are measured in PDF "user space".
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="index">Zero-based index of the character.</param>
        /// <param name="left">Pointer to a double number receiving left position of the character box.</param>
        /// <param name="right">Pointer to a double number receiving right position of the character box.</param>
        /// <param name="bottom">Pointer to a double number receiving bottom position of the character box.</param>
        /// <param name="top">Pointer to a double number receiving top position of the character box.</param>
        [DllImport("pdfium.dll")]
        public static extern void FPDFText_GetCharBox(IntPtr page, int index, ref double left, ref double right, ref double bottom, ref double top);

        /// <summary>
        /// Get the matrix of a particular character.
        /// 
        /// A matrix defines transformation of coordinate from one space to another. 
        /// In PDF, a matrix is defined by the following equations: 
        /// x' = a * x + c * y + e; 
        /// y' = b * x + d * y + f; 
        /// FPDFText_GetMatrix function is used to get a,b,c,d coefficients of the transformation from "text space" to "user space". 
        /// The e, f coefficients are actually the origin position, which can be fetched by FPDFText_GetOrigin function.
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="index">Zero-based index of the character</param>
        /// <param name="a">Pointer to a double value receiving coefficient "a" of the matrix</param>
        /// <param name="b">Pointer to a double value receiving coefficient "b" of the matrix</param>
        /// <param name="c">Pointer to a double value receiving coefficient "c" of the matrix</param>
        /// <param name="d">Pointer to a double value receiving coefficient "d" of the matrix</param>
        [DllImport("pdfium.dll")]
        public static extern void FPDFText_GetMatrix(IntPtr page, int index, ref double a, ref double b, ref double c, ref double d);

        /// <summary>
        /// Get font of a particular character
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="index">Zero-based index of the character.</param>
        /// <returns>A handle to the font used by the particular character. 
        /// This handle can be used in FPDFFont_xxx functions for more information about the font.</returns>
        [DllImport("pdfium.dll")]
        public static extern FPDF_FONT FPDFText_GetFont(IntPtr page, int index);

        /// <summary>
        /// Get font ascent (in 1/1000 em)
        /// </summary>
        /// <param name="font">Handle to a font. Returned by FPDFText_GetFont function.</param>
        /// <returns>The ascent (typically the above-baseline height of letter "h"), measured in 1/1000 of em size. So if a character uses a font size (em size) of 10 points, and it has an ascent value of 500 (meaning half of the em), then the ascent height will be 5 points (5/72 inch).</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFFont_GetAscent(FPDF_FONT font);

        /// <summary>
        /// Get font descent (in 1/1000 em)
        /// </summary>
        /// <param name="font">Handle to a font. Returned by FPDFText_GetFont function.</param>
        /// <returns>The descent (typically the under-baseline height of letter "g"), measured in 1/1000 of em size. Most fonts have a negative descent value.</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFFont_GetDescent(FPDF_FONT font);

        /// <summary>
        /// Get the Name of a font.
        /// </summary>
        /// <param name="font">Handle to a font. Returned by FPDFText_GetFont function.</param>
        /// <returns>A pointer to a null-terminated string that specifies the name of the font. Application can't modify the returned string.</returns>
        [DllImport("pdfium.dll")]
        public static extern string FPDFFont_GetName(FPDF_FONT font);

        /// <summary>
        /// Get the index of a character at or nearby a certain position on the page
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="x">X position in PDF "user space".</param>
        /// <param name="y">Y position in PDF "user space".</param>
        /// <param name="xTolerance">An x-axis tolerance value for character hit detection, in point unit.</param>
        /// <param name="yTolerance">A y-axis tolerance value for character hit detection, in point unit.</param>
        /// <returns>The zero-based index of the character at, or nearby the point (x,y). If there is no character at or nearby the point, return value will be -1. If an error occurs, -3 will be returned.</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFText_GetCharIndexAtPos(IntPtr page, double x, double y, double xTolerance, double yTolerance);

        /// <summary>
        /// Move the character index in different directions and get new character index, from a specific character.
        /// 
        /// FPDFTEXT moves the character pointer according to "stream order". For example, left will move to the previous character, right will move to next character. Because in PDF, "stream order" can be different from "appearance order" (the order that appears to human eyes), so it's possible the moving direction doesn't match the actually position movement. For example, using FPDFTEXT_LEFT may actually result in a character that's all the way down in the page.
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="index">Zero-based index for the current character</param>
        /// <param name="direction">A number indicating the moving direction. 
        /// Can be one of the followings: 
        /// FPDFTEXT_LEFT, 
        /// FPDFTEXT_UP, 
        /// FPDFTEXT_RIGHT, 
        /// FPDFTEXT_DOWN</param>
        /// <returns>Zero-base character index for the new position. -1 if beginning of the page reached; -2 if end of the page reached. -3 for failures.</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFText_GetCharIndexByDirection(IntPtr page, int index, int direction);

        /// <summary>
        /// Extract unicode text string from the page
        /// 
        /// Comment: This function ignores characters without unicode information.
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="start_index">Index for the start characters.</param>
        /// <param name="count">Number of characters to be extracted.</param>
        /// <param name="result">A buffer (allocated by application) receiving the extracted unicodes. The size of the buffer must be able to hold the number of characters plus a terminator.</param>
        /// <returns>Number of characters written into the result buffer, excluding the trailing terminator.</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFText_GetText(IntPtr page, int start_index, int count, ushort[] result);

        /// <summary>
        /// Count number of rectangular areas occupied by a segment of texts.
        /// 
        /// Comment: This function, along with FPDFText_GetRect can be used by applications to detect the position on the page for a text segment, so proper areas can be highlighted or something. FPDFTEXT will automatically merge small character boxes into bigger one if those characters are on the same line and use same font settings.
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="start_index">Index for the start characters</param>
        /// <param name="count">Number of characters</param>
        /// <returns>Number of rectangles. Zero for error.</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFText_CountRects(IntPtr page, int start_index, int count);

        /// <summary>
        /// Get a rectangular area from the result generated by FPDFText_CountRects.
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="rect_index">Zero-based index for the rectangle.</param>
        /// <param name="left">Pointer to a double value receiving the rectangle left boundary.</param>
        /// <param name="top">Pointer to a double value receiving the rectangle top boundary.</param>
        /// <param name="right">Pointer to a double value receiving the rectangle right boundary.</param>
        /// <param name="bottom">Pointer to a double value receiving the rectangle bottom boundary.</param>
        [DllImport("pdfium.dll")]
        public static extern void FPDFText_GetRect(IntPtr page, int rect_index, ref double left, ref double top, ref double right, ref double bottom);

        /// <summary>
        /// Extract unicode text within a rectangular boundary on the page
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="left">Left boundary.</param>
        /// <param name="top">Top boundary.</param>
        /// <param name="right">Right boundary.</param>
        /// <param name="bottom">Bottom boundary.</param>
        /// <param name="buffer">A unicode buffer.</param>
        /// <param name="bufferLength">Number of characters (not bytes) for the buffer, excluding an additional terminator</param>
        /// <returns>If buffer is NULL or buflen is zero, number of characters (not bytes) needed, otherwise, number of characters copied into the buffer.</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFText_GetBoundedText(IntPtr page, double left, double top, double right, double bottom, ref ushort buffer, int bufferLength);

        /// <summary>
        /// Get number of text segments within a rectangular boundary on the page
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="left">Left boundary.</param>
        /// <param name="top">Top boundary.</param>
        /// <param name="right">Right boundary.</param>
        /// <param name="bottom">Bottom boundary.</param>
        /// <returns>Number of segments.</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFText_CountBoundedSegments(IntPtr page, double left, double top, double right, double bottom);

        /// <summary>
        /// Get a particular segment in the result generated by FPDFText_CountBoundedSegments function.
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="seg_index">Zero-based index for the segment</param>
        /// <param name="start_index">Pointer to an integer receiving the start character index for the segment.</param>
        /// <param name="count">Pointer to an integer receiving number of characters in the segment.</param>
        [DllImport("pdfium.dll")]
        public static extern void FPDFText_GetBoundedSegment(IntPtr page, int seg_index, ref int start_index, ref int count);

        /// <summary>
        /// Start a search.
        /// </summary>
        /// <param name="page">Handle to a text page information structure.</param>
        /// <param name="findWhat">A unicode match pattern.</param>
        /// <param name="flags">Option flags.</param>
        /// <param name="start_index">Start from this character. -1 for end of the page.</param>
        /// <returns>A handle for the search context. FPDFText_FindClose must be called to release this handle.</returns>
        [DllImport("pdfium.dll")]
        public static extern IntPtr FPDFText_FindStart(IntPtr page, ushort[] findWhat, int flags, int start_index);

        /// <summary>
        /// Search in the direction from page start to end.
        /// </summary>
        /// <param name="handle">A search context handle returned by FPDFText_FindStart.</param>
        /// <returns>Whether a match is found.</returns>
        [DllImport("pdfium.dll")]
        public static extern bool FPDFText_FindNext(IntPtr handle);

        /// <summary>
        /// Search in the direction from page end to start.
        /// </summary>
        /// <param name="handle">A search context handle returned by FPDFText_FindStart.</param>
        /// <returns>Whether a match is found.</returns>
        [DllImport("pdfium.dll")]
        public static extern bool FPDFText_FindPrev(IntPtr handle);

        /// <summary>
        /// Get the starting character index of the search result.
        /// </summary>
        /// <param name="handle">A search context handle returned by FPDFText_FindStart.</param>
        /// <returns>Index for the starting character.</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFText_GetSchResultIndex(IntPtr handle);

        /// <summary>
        /// Get the number of matched characters in the search result.
        /// </summary>
        /// <param name="handle">A search context handle returned by FPDFText_FindStart.</param>
        /// <returns>Number of matched characters.</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFText_GetSchCount(IntPtr handle);

        /// <summary>
        /// Release a search context.
        /// </summary>
        /// <param name="handle">A search context handle returned by FPDFText_FindStart.</param>
        [DllImport("pdfium.dll")]
        public static extern void FPDFText_FindClose(IntPtr handle);

        /// <summary>
        /// Convert a PDF file to a TXT File.
        /// </summary>
        /// <param name="sourceFile">Path to the PDF file you want to convert.</param>
        /// <param name="destFile">The path of the file you want to save.</param>
        /// <param name="flag">0 for stream order ,1 for appearance order.</param>
        /// <param name="password">A string used as the password for PDF file. If no password needed, empty or NULL can be used.</param>
        /// <returns>TURE for succeed, False for failed.</returns>
        [DllImport("pdfium.dll")]
        public static extern bool FPDFText_PDFToText(string sourceFile, string destFile, int flag, string password);

        //Need Review
        /// <summary>
        /// Convert a PDF page data to a text buffer.
        /// </summary>
        /// <param name="doc">Handle to document. Returned by FPDF_LoadDocument function.</param>
        /// <param name="page_index">Index number of the page. 0 for the first page.</param>
        /// <param name="buf">An output buffer used to hold the text of the page.</param>
        /// <param name="size">Size of the buffer</param>
        /// <param name="flag">0 for stream order ,1 for appearance order.</param>
        /// <returns>If buf is NULL or size is zero, number of characters (not bytes) needed, otherwise, number of characters copied into the buf.</returns>
        [DllImport("pdfium.dll")]
        public static extern int FPDFText_PageToText(IntPtr doc, int page_index, ref char[] buf, int size, int flag);


        #endregion

        [StructLayout(LayoutKind.Sequential)]
        public class FPDF_FONT
        {

        }

        [Flags]
        public enum FPDF_SEARCH_FLAGS
        {
            FPDF_MATCHCASE = 1,
            FPDF_MATCHWHOLEWORD = 2
        }
    }

    public static class PDFActions
    {
        public static void Search(IntPtr page, String text)
        {
            // Set the find flag 
            //int nFlag = 0;// (int)(NativeMethods.FPDF_SEARCH_FLAGS.FPDF_MATCHCASE | NativeMethods.FPDF_SEARCH_FLAGS.FPDF_MATCHWHOLEWORD);
            int nFlag = (int)NativeMethods.FPDF_SEARCH_FLAGS.FPDF_MATCHCASE;

            // Get the search context handle
            ushort[] findWhatBuffer = Array.ConvertAll<byte, ushort>(Encoding.Unicode.GetBytes(text), new Converter<byte, ushort>((input) => { return (ushort)input; }));
            IntPtr pSCHHandle = NativeMethods.FPDFText_FindStart(page, findWhatBuffer, nFlag, 0);

            // Search the text string. 
            bool result = NativeMethods.FPDFText_FindNext(pSCHHandle);

            var index = NativeMethods.FPDFText_GetSchResultIndex(pSCHHandle);

            // var countChar = NativeMethods.FPDFText_GetSchCount(pSCHHandle);

            int charsCount = NativeMethods.FPDFText_CountChars(page);

            int matchedCount = NativeMethods.FPDFText_GetSchCount(pSCHHandle);

            ushort[] buffer = new ushort[100000];
            int extractedCount = NativeMethods.FPDFText_GetText(page, 0, charsCount, buffer);

            // Release the search context 
            //  NativeMethods.FPDFText_FindClose(pSCHHandle);
            char[] charArray = Array.ConvertAll<ushort, char>(buffer, new Converter<ushort, char>((input) => { return (char)input; }));
            String output = new string(charArray);

            //int segmentsCount = NativeMethods.FPDFText_CountBoundedSegments(page, 0, 0, 1000, 1000);
            double left = 0, right = 0, bottom = 0, top = 0;

            NativeMethods.FPDFText_GetCharBox(page, 0, ref left, ref right, ref bottom, ref top);

        }
    }
}
